name: BudgetTracker
options:
  bundleIdPrefix: com.budgettracker
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "14.0"
  createIntermediateGroups: true

targets:
  BudgetTracker:
    type: application
    platform: iOS
    sources:
      - path: BudgetTracker
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.budgettracker.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_VERSION: "5.7"
        INFOPLIST_FILE: BudgetTracker/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        DEVELOPMENT_TEAM: ""
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: BudgetTracker/Info.plist
